version: '3.3'

services:

  postgres_db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tema2_db
    volumes:
      - local_data:/var/lib/postgresql/data
      - ./db/createdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "5432:5432"
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"

  api:
    container_name: rest_api_container
    build: .
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: tema2_db
      DB_HOST: postgres_db
      PORT: 5000
    ports: 
      - "5000:5000"

volumes:
  local_data:
  pgadmin_data:
